config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    root to: "dashboard#show"

    # Addresses
    resources :addresses do
      collection do
        post :update_country
      end
    end

    # Authentication
    resources :oauth_applications

    # Countries
    resources :countries, except: [:show] do
      resources :states, except: [:index, :show]
    end

    # Classifications
    patch :classification, path: "classification/taxon/:taxon_id/product/:product_id", to: "classifications#update"

    # CMS Pages
    resources :cms_pages do
      collection do
        get :filter
      end
      member do
        patch :update_visibility
      end

      resources :cms_sections, except: [:index] do
        member do
          patch :update_position
        end
      end
    end

    # Dashboard
    resource :dashboard, only: [:show]

    # Error forbidden
    get "/forbidden", to: "errors#forbidden", as: :forbidden

    # Menus
    resources :menus do
      resources :menu_items, except: :index do
        member do
          patch :reposition
          delete :remove_icon
        end
      end
    end

    # Options
    resources :option_types do
      resources :option_values, except: :index
    end

    # Orders
    resources :orders, except: [:show] do
      collection do
        get :filter
      end

      member do
        get :channel
        get :new_bill_address
        get :new_ship_address
        get :add_customer_email
        get :new_customer
        get :existing_customer
        post :resend
        put :open_adjustments
        put :close_adjustments
        put :approve
        put :cancel
        put :resume
        put :set_channel
        put :reset_digitals
        put :reset_customer_details
      end

      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :cancel
        end
      end

      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    # Payment Methods
    resources :payment_methods

    # Products
    resources :products do
      collection do
        get :filter
        patch :bulk_update_status
      end
      member do
        post :update_availability
        post :update_cost_currency
        post :update_promotionable
        patch :remove_from_taxon
        post :clone
        get :add_stock, path: "/add_stock/:variant_id"
      end

      resources :digitals, only: [:index, :create, :destroy]
      resources :images
      resources :prices, only: [:index, :create]
      resources :product_properties do
        collection do
          get :prototypes
          post :prototype_properties
        end
      end
      resources :variants
      resources :variants_including_master, only: [:update]
    end

    # Properties
    resources :properties do
      collection do
        get :filtered
      end
    end

    # Prototypes
    resources :prototypes do
      collection do
        get :available
      end

      member do
        post :select
      end
    end

    # Promotions
    resources :promotions do
      collection do
        get :filter
      end

      member do
        post :clone
      end

      resources :promotion_rules do
        get :get_product_option_values
        get :product_options
      end
      resources :promotion_actions
    end
    resources :promotion_categories, except: [:show]

    # Returns
    get "/return_authorizations", to: "returns#return_authorizations", as: :return_authorizations
    get "/customer_returns", to: "returns#customer_returns", as: :customer_returns
    resources :return_items, only: [:update]

    # Reports
    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    # Roles
    resources :roles

    # Refunds
    resources :reimbursement_types
    resources :refund_reasons, except: :show
    resources :return_authorization_reasons, except: :show

    # Search
    resources :search

    # Shipping
    resources :shipping_methods
    resources :shipping_categories
    resources :shipments do
      member do
        %w[ready ship cancel resume pend].each do |state|
          patch state.to_sym
        end
        get :edit_tracking_number
        patch :add_item
        patch :remove_item
        patch :increment_item
        patch :transfer_to_location
        patch :transfer_to_shipment
      end
    end

    # Stores
    resources :stores, except: %i[index show] do
      collection do
        get :switcher
      end
    end

    # States
    resources :states

    # Stock
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end
    resources :stock_items, only: [:create, :update, :destroy]

    # Store Credit
    resources :store_credit_categories

    # Tax
    resources :tax_rates
    resources :tax_categories

    # Taxonomies / Taxons
    resources :taxonomies do
      resources :taxons do
        member do
          patch :reposition
          delete :remove_icon
        end
      end
    end
    resources :taxons, only: [:index, :show] do
      collection do
        post :products_panel
      end
    end

    # Users
    resources :users do
      collection do
        get :filter
      end

      member do
        get :addresses
        get :customer_details
        put :update_address
        get :orders
      end

      resources :store_credits
    end

    # Webhooks
    resources :webhooks_subscribers

    # Zones
    resources :zones
  end

  get Spree.admin_path, to: "admin/dashboard#show", as: :admin
end

app/controllers/spree/admin/orders_controller.rb
module Spree
  module Admin
    class OrdersController < Spree::Admin::BaseController
      include Spree::Admin::OrderConcern

      before_action :load_order, except: %i[index filter new]
      before_action :initialize_order_events, :set_customer_status
      before_action :load_user, only: %i[update]

      def filter
        collection
      end

      def index
        collection
      end

      def new
        @order = scope.create(order_params)
        @user = Spree.user_class.find(params[:user_id]) if params[:user_id].present?

        if @order.save
          sync_order

          redirect_to spree.edit_admin_order_url(@order)
        elsif @order.line_items.empty?
          @order.errors.add(:line_items, I18n.t("spree.admin.errors.messages.blank"))
        end
      end

      def edit
        @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?
      end

      def update
        if @order.update(permitted_resource_params)
          sync_order

          redirect_back fallback_location: spree.edit_admin_order_url(@order)
        elsif @order.line_items.empty?
          @order.errors.add(:line_items, I18n.t("spree.admin.errors.messages.blank"))
        end
      end

      def cancel
        @order.canceled_by(try_spree_current_user)
        dispatch_notice(Spree.t(:order_canceled), :success)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def resume
        @order.resume!
        dispatch_notice(Spree.t(:order_resumed), :success)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def approve
        @order.approved_by(try_spree_current_user)
        dispatch_notice(Spree.t(:order_approved), :success)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def resend
        @order.deliver_order_confirmation_email
        dispatch_notice(Spree.t(:order_email_resent), :success)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def reset_digitals
        @order.digital_links.each(&:reset!)
        dispatch_notice(I18n.t("spree.admin.digitals.downloads_reset"), :notice)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def open_adjustments
        adjustments = @order.all_adjustments.finalized
        adjustments.update_all(state: "open")
        dispatch_notice(Spree.t(:all_adjustments_opened), :success)

        redirect_back fallback_location: spree.admin_order_adjustments_url(@order)
      end

      def close_adjustments
        adjustments = @order.all_adjustments.not_finalized
        adjustments.update_all(state: "closed")
        dispatch_notice(Spree.t(:all_adjustments_closed), :success)

        redirect_back fallback_location: spree.admin_order_adjustments_url(@order)
      end

      def new_bill_address
        @address = @order.build_bill_address(country: current_store.default_country)
      end

      def new_ship_address
        @address = @order.build_ship_address(country: current_store.default_country)
      end

      def new_customer
        @customer_status = "new"
        render :edit
      end

      def existing_customer
        @customer_status = "existing"
        render :edit
      end

      def reset_customer_details
        @order.update(email: nil, billing_address: nil, shipping_address: nil, user: nil)
        redirect_back fallback_location: spree.edit_admin_order_path(@order)
      end

      private

      def set_customer_status
        if @order
          @customer_status = "existing" if @order.user.present?
        end

        @customer_status ||= "new"
      end

      def load_user
        @user = Spree.user_class.find(params[:order][:user_id]) if params[:order][:user_id].present?
      end

      def scope
        current_store.orders.accessible_by(current_ability, :index)
      end

      def model_class
        Spree::Order
      end

      def permitted_resource_params
        params.require(:order).permit(permitted_order_attributes)
      end

      def order_params
        params.permit(:created_by_id, :user_id, :store_id, :channel)
          .with_defaults(created_by_id: try_spree_current_user.try(:id))
      end

      # Used for extensions which need to provide their own custom event links on the order details view.
      def initialize_order_events
        @order_events = %w[approve cancel resume]
      end
    end
  end
end

app/helpers/spree/admin/orders_helper.rb
module Spree
  module Admin
    module OrdersHelper
      # Renders all the extension partials that may have been specified in the extensions
      def event_links(order, events)
        links = []
        events.each do |event|
          next unless order.send("can_#{event}?")

          label = Spree.t(event, scope: "admin.order.events", default: Spree.t(event))
          links << link_to_with_icon(label.capitalize, [event.to_sym, :admin, order], icon: event.to_s + ".svg", data: {turbo_method: :put, turbo_confirm: Spree.t(:order_sure_want_to, event: label)}, class: "btn btn-secondary")
        end
        safe_join(links, "".html_safe)
      end

      def line_item_shipment_price(line_item, quantity)
        Spree::Money.new(line_item.price * quantity, currency: line_item.currency)
      end

      def order_risk_state_badge(order)
        if order.considered_risky
          badge_style = "rgb-hsl-danger"
          badge_text = I18n.t("spree.admin.risky")
        else
          badge_style = if order.complete?
            "rgb-hsl-muted"
          else
            "rgb-hsl-success"
          end

          badge_text = I18n.t("spree.admin.safe")
        end

        content_tag :span, badge_text, class: "badge rounded-pill #{badge_style}"
      end

      def order_payment_state_badge(order)
        badge_style = if order.payment_state == "paid"
          order.complete? ? "rgb-hsl-muted" : "rgb-hsl-success"
        else
          "rgb-hsl-secondary"
        end

        content_tag :span, I18n.t("spree.admin.payment_states.#{order.payment_state}"), class: "badge rounded-pill #{badge_style}"
      end

      def order_shipment_badge(order)
        badge_style = if order.shipment_state == "shipped"
          order.complete? ? "rgb-hsl-muted" : "rgb-hsl-success"
        else
          "rgb-hsl-secondary"
        end

        content_tag :span, I18n.t("spree.admin.shipment_states.#{order.shipment_state}"), class: "badge rounded-pill #{badge_style}"
      end

      def avs_response_code
        {
          "A" => I18n.t("spree.admin.avs_responses.street_address_matches_but_5-digit_and_9_digit_postal_code_do_not_match"),
          "B" => I18n.t("spree.admin.avs_responses.street_address_matches_but_postal_code_not_verified"),
          # TODO MSK translate these
          "C" => "Street address and postal code do not match.",
          "D" => "Street address and postal code match. ",
          "E" => "AVS data is invalid or AVS is not allowed for this card type.",
          "F" => "Card member's name does not match, but billing postal code matches.",
          "G" => "Non-U.S. issuing bank does not support AVS.",
          "H" => "Card member's name does not match. Street address and postal code match.",
          "I" => "Address not verified.",
          "J" => "Card member's name, billing address, and postal code match.",
          "K" => "Card member's name matches but billing address and billing postal code do not match.",
          "L" => "Card member's name and billing postal code match, but billing address does not match.",
          "M" => "Street address and postal code match. ",
          "N" => "Street address and postal code do not match.",
          "O" => "Card member's name and billing address match, but billing postal code does not match.",
          "P" => "Postal code matches, but street address not verified.",
          "Q" => "Card member's name, billing address, and postal code match.",
          "R" => "System unavailable.",
          "S" => "Bank does not support AVS.",
          "T" => "Card member's name does not match, but street address matches.",
          "U" => "Address information unavailable. Returned if the U.S. bank does not support non-U.S. AVS or if the AVS in a U.S. bank is not functioning properly.",
          "V" => "Card member's name, billing address, and billing postal code match.",
          "W" => "Street address does not match, but 9-digit postal code matches.",
          "X" => "Street address and 9-digit postal code match.",
          "Y" => "Street address and 5-digit postal code match.",
          "Z" => "Street address does not match, but 5-digit postal code matches."
        }
      end

      def cvv_response_code
        {
          "M" => "CVV2 Match",
          "N" => "CVV2 No Match",
          "P" => "Not Processed",
          "S" => "Issuer indicates that CVV2 data should be present on the card, but the merchant has indicated data is not present on the card",
          "U" => "Issuer has not certified for CVV2 or Issuer has not provided Visa with the CVV2 encryption keys",
          "" => "Transaction failed because wrong CVV2 number was entered or no CVV2 number was entered"
        }
      end
    end
  end
end

app/views/spree/admin/orders/_add_line_item.html.erb
<div id="add-line-item" data-hook class="card">
  <div class="card-header">
    <h5 class="card-title"><%= Spree.t(:products) %></h5>
  </div>
  <div class="card-body">
    <div data-hook="add_product_name" class="form-group">
      <%= form_with model: @order, url: spree.admin_order_line_items_path(@order), method: :post, data: { controller: "form-validation" } do |f| %>
       <%= f.fields_for :line_items_attributes do |li| %>
          <div class="form-group form-floating">
            <%= li.select :variant_id, [], {}, name: 'line_item[variant_id]', class: 'form-select',
                                                      placeholder: I18n.t('spree.admin.order.search_for_a_product_or_variant'),
                                                      data: { action: 'change->form-validation#validate',
                                                      controller: 'ts--search-variant',
                                                      ts__search_variant_debug_value: false,
                                                      ts__search_variant_uri_value: '/api/v2/platform/variants',
                                                      ts__search_variant_fields_value: ['name', 'sku'],
                                                      ts__search_variant_ransack_value: ['product_name_or_sku_eligible_only'],
                                                      ts__search_variant_custom_params_value: [ ['[image_transformation]size', '100x100'] ],
                                                      ts__search_variant_include_value: 'images,stock_items.stock_location'

                                                    } %>

            <%= label_tag :variant_id, I18n.t('spree.admin.order.products'), class: 'form-label' %>
            <%= hidden_field nil, 'line_item[quantity]', value: "1" %>
          </div>
          <%= f.submit I18n.t('spree.admin.order.products'), class: 'btn btn-secondary', data: { form_validation_target: "submitBtn" } %>
        <% end %>
      <% end %>
    </div>

    <% if @order.line_items.empty? %>
      <div class="alert alert-warning mb-0">
        <%= Spree.t(:your_order_is_empty_add_product) %>
      </div>
    <% else %>
      <%= render partial: 'line_items', locals: { order: @order} %>
    <% end %>
  </div>
</div>

app/views/spree/admin/orders/_adjustments.html.erb
<% if adjustments.eligible.exists? %>
  <div class="card mb-3">
    <div class="card-header">
      <h5 class="card-title mb-0 h6">
        <%= title %>
      </h5>
    </div>
    <div class="table-responsive bg-white">
      <table class="table">
        <thead class="text-muted">
          <tr>
            <th><%= I18n.t('spree.admin.name') %></th>
            <th><%= I18n.t('spree.admin.amount') %></th>
          </tr>
        </thead>
        <tbody id="order-charges" data-hook="order_details_adjustments">
          <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td>
                <strong><%= label %>:</strong>
              </td>
              <td class="total">
                <span>
                  <%= Spree::Money.new(
                    adjustments.sum(&:amount),
                    currency: adjustments.first.order.try(:currency)
                  ) %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/spree/admin/orders/_currency.html.erb
<sa-card>
  <sa-header>
    <h5><%= I18n.t('spree.admin.order.currency') %></h5>
    <h5><span class="badge rgb-hsl-success"><%= currency_symbol(@order.currency) %> <%= @order.currency %></span></h5>
  </sa-header>
  <sa-body>
    <% currency_label_text = @order.item_count > 0 ? I18n.t('spree.admin.order.the_order_currency_is_locked_once_items_are_added') : Spree.t(:currency) %>
    <%= form_with model: [:admin, @order], data: { controller: "form-validation" } do |f| %>
      <%= f.field_container :currency do %>
        <%= f.select :currency, supported_currency_options, { include_blank: false }, disabled: @order.item_count > 0,
                                                              placeholder: I18n.t('spree.admin.order.set_order_currency'),
                                                              data: { controller: 'ts--select',
                                                                      action: 'change->form-validation#validate' } %>
        <%= f.label :currency, currency_label_text %>
      <% end %>
      <%= f.submit I18n.t('spree.admin.order.set_order_currency'), class: 'btn btn-secondary', data: { form_validation_target: "submitBtn" } %>
    <% end %>
  </sa-body>
</sa-card>

app/views/spree/admin/orders/_invoice.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div class="flex-fill">
      <h5 class="card-title">Invoice</h5>
    </div>

    <div>
      <%= link_to I18n.t('spree.admin.order.email_copy_of_invoice_to_customer'), 'spree.ship_admin_shipment_path(shipment.id)', class: 'btn btn-secondary btn-sm', data: { turbo_method: :patch } , title: I18n.t('spree.admin.order.mark_as_shipped') %>
    </div>
  </div>
  <div class="card-body" id="order_tab_summary">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span data-hook='admin_order_tab_subtotal_title'><%= Spree.t(:subtotal) %></span>
        <span id='item_total'>
          <%= @order.display_item_total.to_html %>
        </span>
      </li>

      <% if @order.ship_total > 0 %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <small data-hook='admin_order_tab_ship_total_title'><%= Spree.t(:ship_total) %></small>
          <span id='ship_total'>
            <%= @order.display_ship_total.to_html %>
          </span>
        </li>
      <% end %>

      <% if @order.included_tax_total != 0 %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <small data-hook='admin_order_tab_included_tax_title'><%= Spree.t(:tax_included) %></small>
          <span class="badge rounded-pill rgb-hsl-secondary" id='included_tax_total'>
            <%= @order.display_included_tax_total.to_html %>
          </span>
        </li>
      <% end %>

      <% if @order.additional_tax_total != 0 %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <small data-hook='admin_order_tab_additional_tax_title'><%= Spree.t(:tax) %></small>
          <span class="badge rounded-pill rgb-hsl-secondary" id='additional_tax_total'>
            <%= @order.display_additional_tax_total.to_html %>
          </span>
        </li>
      <% end %>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        <small data-hook='admin_order_tab_total_title'><%= Spree.t(:total) %></small>
        <span id='order_total'>
          <%= @order.display_total.to_html %>
        </span>
      </li>
    </ul>
  </div>
</div>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="table-responsive border-0 rounded bg-white">
    <table class="table line-items" data-hook="line-items">
      <thead class="text-muted">
        <tr>
          <th colspan="2"><%= Spree.t(:name) %></th>
          <th class="text-center"><%= Spree.t(:price) %></th>
          <th class="text-center"><%= Spree.t(:quantity) %></th>
          <th class="text-center"><%= Spree.t(:total_price) %></th>
          <th class="orders-actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
        </tr>
      </thead>
      <tbody>
        <% order.line_items.each do |item| %>
          <tr class="line-item" id="line-item-<%= item.id %>">
            <td class="line-item-image image text-center">
              <%= link_to small_image(item.variant), spree.edit_admin_product_path(item.variant.product) %>
            </td>
            <td class="line-item-name text-center">
              <%= link_to item.name, espree.dit_admin_product_path(item.variant.product) %>
              <br>
              <%= "(#{item.options_text})" if item.options_text.present? %>
            </td>
            <td class="line-item-price text-center">
              <%= item.single_money.to_html %>
            </td>
            <td class="line-item-qty-edit" style="width:120px;" data-controller="number-increment form-validation">
              <%= form_with url: spree.admin_order_line_item_path(@order, item), method: :patch do %>
                <%= render partial: 'spree/admin/shared/number_toggle', locals: { value: item.quantity, attribute: 'line_item[quantity]' } %>
              <% end %>
            </td>
            <td class="line-item-total text-center">
              <%= line_item_shipment_price(item, item.quantity) %>
            </td>
            <td>
              <span class="d-flex justify-content-center">
                <%= link_to_delete(item, { url: spree.admin_order_line_item_path(@order, item) }) if can? :destroy, item %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/_orders_list.html.erb
<%= turbo_frame_tag "#{plural_resource_name(@collection).downcase}-page-#{@pagy.page}" do %>
  <% @collection.each do |order| %>
    <% if order.complete? %>
        <% muted_text_class = 'text-muted' %>
      <% else %>
        <% muted_text_class = '' %>
    <% end %>

    <g-tr style=" grid-template-columns: 2fr 3fr 2fr 1fr 1fr 1fr 1fr; " class="<%= muted_text_class %>">
      <%= link_to spree.edit_admin_order_path(order), class: muted_text_class do %>
        <%= order.number %>
      <% end %>

      <%= link_to spree.edit_admin_order_path(order), class: muted_text_class do %>
        <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
      <% end %>

      <g-td class="dropdown">
        <% if order.user %>
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= order.email %>
          </button>

          <ul class="dropdown-menu">
            <li><%= link_to order.email, spree.edit_admin_user_path(order.user), class: 'dropdown-item' %></li>
          </ul>
        <% else %>
          <%= mail_to order.email %>
        <% end %>
      </g-td>

      <%= link_to spree.edit_admin_order_path(order) do %>
        <%= order_risk_state_badge(order) %>
      <% end %>

      <%= link_to spree.edit_admin_order_path(order) do %>
        <% if order.payment_state %>
          <%= order_payment_state_badge(order) %>
        <% end %>
      <% end %>

      <% if Spree::Order.checkout_step_names.include?(:delivery) %>
        <%= link_to spree.edit_admin_order_path(order) do %>
          <% if order.shipment_state %>
            <%= order_shipment_badge(order) %>
          <% end %>
        <% end %>
      <% end %>

      <%= link_to spree.edit_admin_order_path(order), class: muted_text_class do %>
        <%= order.display_total.to_html %>
      <% end %>
    </g-tr>
  <% end %>

  <% unless @pagy.nil? %>
    <%= render "spree/admin/shared/next_page" %>
  <% end %>
<% end %>

app/views/spree/admin/orders/_risk_analysis.html.erb
<fieldset id="risk_analysis">
  <legend><%= "#{Spree.t(:risk_analysis)}: #{Spree.t(:not) unless @order.is_risky?} #{Spree.t(:risky)}" %></legend>
  <div class="table-responsive border rounded">
    <table class="table table-condensed border rounded">
      <thead class="text-muted">
        <th><%= I18n.t('spree.admin.risk') %></th>
        <th><%= I18n.t('spree.admin.status') %></th>
      </thead>
      <tbody id="risk-analysis" data-hook="order_details_adjustments" class="with-border">
        <tr>
          <td>
            <strong><%= Spree.t(:failed_payment_attempts) %>:</strong>
          </td>
          <td>
            <span class="badge rounded-pill bg-<%= @order.payments.failed.size > 0 ? 'void' : 'complete' %>">
              <%= link_to "#{Spree.t 'payments_count', count: @order.payments.failed.size, default: pluralize(@order.payments.failed.size, Spree.t(:payment))}", spree.admin_order_payments_path(@order) %>
            </span>
          </td>
        </tr>

        <tr>
          <td><strong><%= Spree.t(:avs_response) %>:</strong></td>
          <td>
            <span class="badge rounded-pill bg-<%= latest_payment.is_avs_risky? ? 'void' : 'complete' %>">
              <% if latest_payment.is_avs_risky? %>
                <%= "#{Spree.t(:error)}: #{avs_response_code[latest_payment.avs_response]}" %>
              <% else %>
                <%= Spree.t(:success) %>
              <% end %>
            </span>
          </td>
        </tr>

        <tr>
          <td><strong><%= Spree.t(:cvv_response) %>:</strong></td>
          <td>
            <span class="badge rounded-pill bg-<%= latest_payment.is_cvv_risky? ? 'void' : 'complete' %>">
              <% if latest_payment.is_cvv_risky? %>
                <%= "#{Spree.t(:error)}: #{cvv_response_code[latest_payment.cvv_response_code]}" %>
              <% else %>
                <%= Spree.t(:success) %>
              <% end %>
            </span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</fieldset>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon Spree.t(:new_order), new_admin_order_path, class: "btn-primary btn", icon: 'plus-square.svg', id: 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<%#-------------------------------------------------%>
<%# Index Table                                     %>
<%#-------------------------------------------------%>
<% content_for :index_table_filter_tabs do %>
  <%= link_to Spree.t('admin.orders.all'), spree.admin_orders_path, class: "#{'active' if params[:q][:payment_state_not_eq].blank? && params[:q][:shipment_state_not_eq].blank?}" %>
  <%= link_to Spree.t('admin.orders.unpaid'), params.merge({q: {payment_state_not_eq: :paid}}).permit!, class: "#{'active' if params[:q][:payment_state_not_eq] == 'paid'}" %>
  <%= link_to Spree.t('admin.orders.unfulfilled'), params.merge({q: {shipment_state_not_eq: :shipped}}).permit!, class: "#{'active' if params[:q][:shipment_state_not_eq] == 'shipped'}" %>
<% end %>

<% content_for :index_table_filter_buttons do %>
  <%= link_to I18n.t('spree.admin.more_filters'), spree.filter_admin_orders_path(request.query_parameters), class: "btn btn-secondary", data: {turbo_frame: :offcanvas} %>
<% end %>

<% content_for :index_table do %>
  <% if @collection.any? %>
    <g-responsive>
      <g-table class="gridtable-hover" id="listing_orders">
        <g-thead>
          <g-tr style=" grid-template-columns: 2fr 3fr 2fr 1fr 1fr 1fr 1fr; ">
            <g-th><%= I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></g-th>
            <g-th><%= I18n.t('spree.admin.date') %></g-th>
            <g-th><%= I18n.t('spree.admin.customer') %></g-th>
            <g-th><%= I18n.t('spree.admin.risk') %></g-th>
            <g-th><%= I18n.t('spree.admin.payment') %></g-th>
            <g-th><%= I18n.t('spree.admin.shipment') %></g-th>
            <g-th><%= I18n.t('spree.admin.total') %></g-th>
          </g-tr>
        </g-thead>

        <g-tbody>
          <%= render partial: "orders_list" %>
        </g-tbody>
      </g-table>
    </g-responsive>
  <% else %>
    <div class="text-center no-objects-found m-5">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>
    </div>
  <% end %>
<% end %>

<%#-------------------------------------------------%>
<%# Render the index_table partial passing a        %>
<%# search_field_value and search_field_placeholder %>
<%# text if you want to add a search bar            %>
<%#-------------------------------------------------%>
  <%= render partial: "spree/admin/shared/index_table",
             locals: { search_record: :number_i_cont,
                       search_placeholder: I18n.t('spree.admin.products.search_all_orders_by_number') } %>